export KITTY_CONFIG_DIRECTORY="${KITTY_CONFIG_DIRECTORY:-$XDG_CONFIG_HOME/kitty}"
export KITTY_CACHE_DIRECTORY="${KITTY_CACHE_DIRECTORY:-$XDG_CACHE_HOME/kitty}"
export EDITOR="${EDITOR:-$HOME/.local/bin/nvim}"
export VISUAL="${VISUAL:-$EDITOR}"
export GNUPGHOME="${GNUPGHOME:-$HOME/.local/share/gnupg}"
export PASSWORD_STORE_DIR="${PASSWORD_STORE_DIR:-$HOME/.local/share/pass}"
export GDRIVE="${GDRIVE:-/mnt/chromeos/GoogleDrive/MyDrive}"
export PRJROOT="${PRJROOT:-$HOME/src}"
export CODEX_HOME="${CODEX_HOME:-$HOME/.local/share/codex}"
export CODEX_STATE="${CODEX_STATE:-$HOME/.local/state/codex}"
export GOPATH="${GOPATH:-$HOME/go}"
export GOBIN="${GOBIN:-$GOPATH/bin}"

path_prepend "$HOME/.go/bin"
path_prepend "$GOBIN"
