# Paths mode: one-shot filesystem path entry points.
map --new-mode mode_paths --on-unknown end --on-action end ctrl+space>p
map --mode mode_paths shift+/ show_keymap_help
map --mode mode_paths n send_text normal,application fzf.nameddirs cd\r
map --mode mode_paths f launch --type=os-window --os-window-state=maximized --cwd=current kitten choose-files
map --mode mode_paths d launch --type=os-window --os-window-state=maximized --cwd=current kitten choose-files --mode=dir
map --mode mode_paths esc pop_keyboard_mode
