# Scrollback mode: one-shot selection, extraction, inspection.
map --new-mode mode_scrollback --on-unknown end --on-action end ctrl+space>s
map --mode mode_scrollback shift+/ show_keymap_help

# inspection
map --mode mode_scrollback s kitty_scrollback_nvim --config screen_auto
map --mode mode_scrollback a kitty_scrollback_nvim --config all_ansi
map --mode mode_scrollback c kitty_scrollback_nvim --config selection_keep
map --mode mode_scrollback g kitty_scrollback_nvim --config last_cmd_output
map --mode mode_scrollback n kitty_scrollback_nvim --config last_non_empty_output
map --mode mode_scrollback f kitty_scrollback_nvim --config first_cmd_output_on_screen
map --mode mode_scrollback r show_scrollback

# terminal text -> clipboard
#map --mode mode_scrollback y clip_selection
#map --mode mode_scrollback p primary_selection
#map --mode mode_scrollback x clip_screen
#map --mode mode_scrollback b clip_scrollback
map --mode mode_scrollback 1 clip_last_cmd
#map --mode mode_scrollback v clip_last_visited

# --- aliases: external pixel capture ---
#action_alias shot_clip      launch --type=background ~/.local/bin/kitty-shot-clip
action_alias shot_primary   launch --type=background ~/.local/bin/kitty-shot-primary
#action_alias shot_save_copy launch --type=background ~/.local/bin/kitty-shot-save-copy

# pixel capture -> clipboard
#map --mode mode_scrollback m shot_clip
map --mode mode_scrollback M shot_primary
#map --mode mode_scrollback o shot_save_copy

# marks
#map --mode mode_scrollback e toggle_marker iregex 1 \\b(ERROR|ERR|FATAL|PANIC)\\b 2 \\b(WARN|WARNING)\\b
map --mode mode_scrollback . create_marker
map --mode mode_scrollback , remove_marker
map --mode mode_scrollback ] scroll_to_mark next
map --mode mode_scrollback [ scroll_to_mark prev

map --mode mode_scrollback esc pop_keyboard_mode
