# Hints mode: one-shot visible-text selection.
map --new-mode hints --on-unknown end --on-action end ctrl+space>h
map --mode hints shift+/ show_keymap_help
map --mode hints u open_url_with_hints
map --mode hints p kitten hints --type=path --program -
map --mode hints o kitten hints --type=path
map --mode hints l kitten hints --type=line --program -
map --mode hints w kitten hints --type=word --program -
map --mode hints h kitten hints --type=hash --program -
map --mode hints n kitten hints --type=linenum
map --mode hints y kitten hints --type=hyperlink
map --mode hints esc pop_keyboard_mode
