# Launchers mode: one-shot path/file entry points.
map --new-mode mode_launchers --on-unknown end --on-action end ctrl+space>l
map --mode mode_launchers shift+/ show_keymap_help
map --mode mode_launchers v launch --type=tab --cwd=current --add-to-session=. kitty-launch-with-cwd nvim
map --mode mode_launchers b launch --type=tab --cwd=current --add-to-session=. br
map --mode mode_launchers y launch --type=tab --cwd=current --add-to-session=. yazi
map --mode mode_launchers esc pop_keyboard_mode
