# Signals and utility mode: one-shot shell-facing actions.
map --new-mode signals --on-unknown end --on-action end ctrl+space>x
map --mode signals shift+/ show_keymap_help
map --mode signals b kitten broadcast
map --mode signals c copy_to_clipboard
map --mode signals v paste_from_clipboard
map --mode signals x send_signal SIGINT
map --mode signals u kitten unicode_input
map --mode signals d clear_terminal reset active
map --mode signals esc pop_keyboard_mode
