#!/usr/bin/env sh
# generated: ripgrep env
# shellcheck shell=sh

: "${DOTS_REPO:=src}"
: "${DOTS_DIR:=dots}"
: "${DOTS_HOME:=$XDG_DATA_HOME/_404/dots}"
: "${XDG_CONFIG_HOME:=$DOTS_HOME/.config}"
: "${XDG_DATA_HOME:=$HOME/.local/share}"
: "${XDG_OPT_HOME:=$DOTS_HOME/.local/opt}"
: "${XDG_STATE_HOME:=$HOME/.local/state}"
: "${XDG_CACHE_HOME:=$HOME/.cache}"
: "${TOOL_PATH_HOME:=$HOME/.local/bin}"
: "${TOOL_PREFIX_HOME:=${TOOL_PATH_HOME%/bin}}"
[ "$TOOL_PREFIX_HOME" != "$TOOL_PATH_HOME" ] || TOOL_PREFIX_HOME=$(dirname "$TOOL_PATH_HOME")

export DOTS_REPO DOTS_DIR DOTS_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_OPT_HOME XDG_STATE_HOME XDG_CACHE_HOME TOOL_PATH_HOME TOOL_PREFIX_HOME

: "${RIPGREP_PREFIX:=$XDG_OPT_HOME/ripgrep}"
: "${RIPGREP_STATE:=$XDG_STATE_HOME/_404/ripgrep}"
: "${RIPGREP_CACHE:=$XDG_CACHE_HOME/_404/ripgrep}"
: "${RIPGREP_BIN_HOME:=$XDG_OPT_HOME/ripgrep/bin}"
: "${RIPGREP_SHARE_HOME:=$XDG_OPT_HOME/ripgrep/share}"

export RIPGREP_PREFIX RIPGREP_STATE RIPGREP_CACHE RIPGREP_BIN_HOME RIPGREP_SHARE_HOME


