github.com:
    users:
        fatb4f:
            oauth_token: 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
    git_protocol: https
    user: fatb4f
    oauth_token: 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
