# shellcheck shell=bash

: "${HOME:?HOME is required}"
: "${XDG_CONFIG_HOME:=$HOME/.config}"
: "${XDG_STATE_HOME:=$HOME/.local/state}"
: "${XDG_DATA_HOME:=$HOME/.local/share}"

DOTCTL_CONFIG_HOME="${DOTCTL_CONFIG_HOME:-$XDG_CONFIG_HOME/dotctl}"
DOTCTL_AUDIT_HOME="${DOTCTL_AUDIT_HOME:-$XDG_CONFIG_HOME/dotfiles-audit}"
DOTCTL_AUDIT_STATE_HOME="${DOTCTL_AUDIT_STATE_HOME:-$XDG_STATE_HOME/dotfiles-audit}"
DOTCTL_GIT_HOME="${DOTCTL_GIT_HOME:-$XDG_DATA_HOME/dotctl/backend/git}"
DOTCTL_GIT_CACHE_HOME="${DOTCTL_GIT_CACHE_HOME:-$XDG_CACHE_HOME/dotctl/backend/git}"
DOTCTL_GIT_STATE_HOME="${DOTCTL_GIT_STATE_HOME:-$XDG_STATE_HOME/dotctl/backend/git}"
DOTCTL_GIT_DATA_HOME="${DOTCTL_GIT_DATA_HOME:-$XDG_DATA_HOME/dotctl/backend/git}"
DOTCTL_GIT_POLICY="${DOTCTL_GIT_POLICY:-$DOTCTL_CONFIG_HOME/policy/git.cue}"

DOTCTL_GIT_OBSERVE_JSON="${DOTCTL_GIT_OBSERVE_JSON:-$DOTCTL_GIT_CACHE_HOME/observe.json}"
DOTCTL_GIT_CURRENT_JSON="${DOTCTL_GIT_CURRENT_JSON:-$DOTCTL_GIT_STATE_HOME/current.json}"
DOTCTL_GIT_DIRTY_JSON="${DOTCTL_GIT_DIRTY_JSON:-$DOTCTL_GIT_STATE_HOME/dirty.json}"
DOTCTL_GIT_LAST_VETTED_JSON="${DOTCTL_GIT_LAST_VETTED_JSON:-$DOTCTL_GIT_DATA_HOME/last-vetted.json}"
DOTCTL_GIT_TRACKED_JSON="${DOTCTL_GIT_TRACKED_JSON:-$DOTCTL_GIT_DATA_HOME/tracked.json}"
DOTCTL_GIT_REFS_JSON="${DOTCTL_GIT_REFS_JSON:-$DOTCTL_GIT_DATA_HOME/refs.json}"

DOTCTL_AUDIT_TARGETS_DEFAULT=(
  ".config/bin"
  ".config/broot"
  ".config/nvim"
  ".config/uv"
)
