# ~/.config/environment.d/10-path.conf
PATH=/home/_404/.local/share/cargo/bin/:/home/_404/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
XDG_CACHE_HOME=/home/_404/.cache
XDG_CONFIG_HOME=/home/_404/.config
XDG_DATA_HOME=/home/_404/.local/share
XDG_STATE_HOME=/home/_404/.local/state
XDG_CONFIG_DIRS=/etc/xdg
XDG_DATA_DIRS=/usr/local/share:/usr/share
