EDITOR=/home/_404/.local/bin/nvim
VISUAL=/home/_404/.local/bin/nvim
GNUPGHOME=/home/_404/.local/share/gnupg
PASSWORD_STORE_DIR=/home/_404/.local/share/pass
GDRIVE=/mnt/chromeos/GoogleDrive/MyDrive
PRJROOT=/home/_404/.local/share/src
CODEX_HOME=/home/_404/.config/codex
CODEX_STATE=/home/_404/.local/state/codex
