ANDROID_USER_HOME=/home/_404/.local/share/android
CARGO_HOME=/home/_404/.local/share/cargo
RUSTUP_HOME=/home/_404/.local/share/rustup
HISTFILE=/home/_404/.local/state/bash/history
LESSHISTFILE=/home/_404/.local/state/lesshst
PIP_CACHE_DIR=/home/_404/.cache/pip
PYTHONPYCACHEPREFIX=/home/_404/.cache/python/pycache
PYTEST_ADDOPTS=-o cache_dir=/home/_404/.cache/pytest
RUFF_CACHE_DIR=/home/_404/.cache/ruff
UV_CACHE_DIR=/home/_404/.cache/uv
